# Generated by Django 4.1.12 on 2023-10-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guest'),
        ('accounts', '0002_useraccount_date_joined'),
    ]

    operations = [
    ]
